# Generated by Django 5.2.5 on 2025-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_supervisor_alter_project_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manual_progress',
            field=models.PositiveIntegerField(blank=True, help_text='Manual progress percentage (0-100). If not set, auto-calculated based on status.', null=True),
        ),
    ]
