# Generated by Django 5.2.5 on 2025-09-13 16:07

import apps.projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_manual_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.projects.models.project_note_image_upload_path),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
