# Generated by Django 5.2.5 on 2025-11-05 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectnote_image_projectnote_mentioned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'priority'], name='projects_pr_status_d9e5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['due_date', 'status'], name='projects_pr_due_dat_2c4476_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['completed_date'], name='projects_pr_complet_095e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'status'], name='projects_pr_is_acti_189799_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['assigned_to', 'is_active'], name='projects_pr_assigne_f31b09_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['supervisor', 'is_active'], name='projects_pr_supervi_6d374d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_name'], name='projects_pr_client__447719_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['project', 'is_active'], name='projects_pr_project_780d40_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['user', 'is_active'], name='projects_pr_user_id_3202c7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['role', 'is_active'], name='projects_pr_role_1e1f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'created_at'], name='projects_pr_project_32a72c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['is_confidential'], name='projects_pr_is_conf_4ce566_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['document_type'], name='projects_pr_documen_747ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['project', 'created_at'], name='projects_pr_project_cc03c1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['is_internal'], name='projects_pr_is_inte_3b5c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttagassignment',
            index=models.Index(fields=['project', 'tag'], name='projects_pr_project_ef5a7e_idx'),
        ),
    ]
