# Generated by Django 5.2.5 on 2025-08-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='source_project',
            field=models.OneToOneField(blank=True, help_text='Link to the internal project that this portfolio entry showcases', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_entry', to='projects.project'),
        ),
    ]
