# Generated by Django 5.2.5 on 2025-10-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
    ]
