# Generated by Django 5.2.5 on 2025-10-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_unique_together_remove_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
