# Generated by Django 5.2.5 on 2025-10-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_expense_user_remove_income_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='user',
        ),
    ]
