# Generated by Django 5.2.5 on 2025-11-04 11:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_budget_user_remove_savingsgoal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before currency conversion', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency_original',
            field=models.ForeignKey(blank=True, help_text='Original currency before conversion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_originals', to='wallet.currency'),
        ),
        migrations.AddField(
            model_name='income',
            name='amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before currency conversion', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='income',
            name='currency_original',
            field=models.ForeignKey(blank=True, help_text='Original currency before conversion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_originals', to='wallet.currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before currency conversion', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency_original',
            field=models.ForeignKey(blank=True, help_text='Original currency before conversion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_originals', to='wallet.currency'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial balance when wallet was created', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Amount in wallet's currency (after conversion)", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Amount in wallet's currency (after conversion)", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Amount in wallet's currency (after conversion)", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current balance (updated automatically with transactions)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
