# Generated by Django 5.2.5 on 2025-11-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_expense_amount_original_expense_currency_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the base currency for exchange rates?'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate to base currency (cached from live API)', max_digits=15),
        ),
    ]
