# Generated by Django 5.2.5 on 2025-11-04 18:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_currency_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_rwf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount converted to RWF (base currency for totals)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='amount_rwf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount converted to RWF (base currency for totals)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount_rwf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount converted to RWF (base currency for totals)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_rwf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance converted to RWF (base currency for totals)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
