# Generated by Django 5.2.5 on 2025-11-05 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectnote_image_projectnote_mentioned_users'),
        ('wallet', '0008_subscription_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'wallet'], name='wallet_expe_date_56798e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'project'], name='wallet_expe_date_a2c0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='wallet_expe_date_a1cd84_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_recurring', 'next_occurrence'], name='wallet_expe_is_recu_94fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='wallet_expe_categor_2719f3_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by'], name='wallet_expe_created_ac0105_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date', 'wallet'], name='wallet_inco_date_03f8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date', 'project'], name='wallet_inco_date_8ffa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['-date'], name='wallet_inco_date_1d5dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['is_recurring', 'next_occurrence'], name='wallet_inco_is_recu_6fb73a_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['category'], name='wallet_inco_categor_c30ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['created_by'], name='wallet_inco_created_52a38c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_billing_date', 'is_active'], name='wallet_subs_next_bi_4fef21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'is_active'], name='wallet_subs_status_b406b0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_cycle'], name='wallet_subs_billing_5bb7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['wallet'], name='wallet_subs_wallet__29a7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['category'], name='wallet_subs_categor_871134_idx'),
        ),
    ]
